name: Hexo Deploy

on:
  push:
    branches:
      - blog-source

jobs:
  build-to-deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v3.0.2
        with:
          ref: blog-source
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{secrets.HEXO_DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$ACTION_DEPLOY_KEY"
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "hongwei.han@qq.com"
          git config --global user.name "atecher"
          npm install hexo-cli -g
          npm install hexo-neat --save
          npm install

      - name: Generate files
        run: |
          hexo clean
          hexo generate
          echo "pwd: "`pwd`

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
          branch: master
          folder: public

#  mirror_to_coding:
#    runs-on: ubuntu-latest
#    steps:
#      - name: 'Checkout'
#        uses: actions/checkout@v3.0.2
#      - name: 'Mirror to coding'
#        uses: pixta-dev/repository-mirroring-action@v1
#        with:
#          target_repo_url: git@e.coding.net:Atecher/atecher/atecher-blog.git
#          ssh_private_key: ${{secrets.CODING_PRIVATE_KEY}}
