name: Hexo Deploy

on:
  push:
    branches:
      - blog-source

jobs:
  build-to-deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          ref: blog-source
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12'

      - name: Setup Hexo
        env:
          ACTION_DEPLOY_KEY: ${{secrets.HEXO_DEPLOY_KEY}}
        run: |
          mkdir -p ~/.ssh/
          echo "$ACTION_DEPLOY_KEY" > ~/.ssh/id_rsa
          echo "$ACTION_DEPLOY_KEY"
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.email "hongwei.han@qq.com"
          git config --global user.name "atecher"
          npm install hexo-cli -g
          npm install

      - name: Generate files
        run: |
          hexo clean
          hexo generate
          echo "pwd: "`pwd`

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          ssh-key: ${{secrets.HEXO_DEPLOY_KEY}}
          branch: master
          folder: public
#
#      - name: Qiniu
#        uses: Hanlin-Dong/hexo-to-qiniu-action@v1-full
#        with:
#          bucket: atecher-blog
#          access-key: ${{secrets.QINIU_ACCESS_KEY}}
#          secret-key: ${{secrets.QINIU_SECRET_KEY}}
#          base-folder: ./public
#          domain: "http://www.atecher.com"
#          sub-domain: ""


#      - name: sync
#        uses: wearerequired/git-mirror-action@master
#        env:
#          SSH_PRIVATE_KEY: ${{secrets.HEXO_DEPLOY_KEY}}
#        with:
#          source-repo: "git@github.com:atecher/atecher.github.io.git"
#          destination-repo: "git@gitee.com:atecher/atecher.git"

#      - name: 'Mirror to gitee'
#        uses: pixta-dev/repository-mirroring-action@v1
#        with:
#          target_repo_url: git@gitee.com:atecher/atecher.git
#          ssh_private_key: ${{secrets.HEXO_DEPLOY_KEY}}
