name: Sync To Gitee

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: sync
        uses: wearerequired/git-mirror-action@master
        env:
          SSH_PRIVATE_KEY: ${{secrets.HEXO_DEPLOY_KEY}}
        with:
          source-repo: "git@github.com:atecher/atecher.github.io.git"
          destination-repo: "git@gitee.com:atecher/atecher.git"